"""redes-neuronales-2024-guia-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/marcos626/f1994542d9280d4a2d6b234aebbdf230/redes-neuronales-2024-guia-4.ipynb

# Integración numérica de ODEs

En este práctico introduciremos los métodos de **Euler** y de **RK4** (Runge-Kutta de orden 4) de integración numérica de Ecuaciones Diferenciales Ordinarias (ODEs).

## Ejercicio 1) Importando librerías

Importe las librerías `numpy` para operar con arrays, `scipy` para utilizar rutinas de algebra lineal y `matplotlib.pyplot` para graficar.
"""

import numpy as np
import scipy as sp
import scipy.linalg as linalg
import matplotlib.pyplot as plt
from ode import euler, rk4, integrador_ode


### Ecuaciones Diferenciales Ordinarias (ODEs)
# Ejercicio 5) Ecuación Logística

# 5.1)

def f(x,t,p):
    """
    r = p[0]
    K = p[1]
    """
    return np.array([p[0]*x[0]*(1-x[0]/p[1])])

# 5.2)
